#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarPark

#include "../../Include/SDK/Basic.hpp"

#include "../../Include/SDK/BP_CarPark_classes.hpp"
#include "../../Include/SDK/BP_CarPark_parameters.hpp"


namespace SDK
{

// Function BP_CarPark.BP_CarPark_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CarPark_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CarPark_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

