#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CL_ModHook

#include "Basic.hpp"

#include "BP_CL_ModHook_classes.hpp"
#include "BP_CL_ModHook_parameters.hpp"


namespace SDK
{

// Function BP_CL_ModHook.BP_CL_ModHook_C.ExecuteUbergraph_BP_CL_ModHook
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CL_ModHook_C::ExecuteUbergraph_BP_CL_ModHook(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CL_ModHook_C", "ExecuteUbergraph_BP_CL_ModHook");

	Params::BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CL_ModHook.BP_CL_ModHook_C.PostSpawnVehicle
// (Event, Public, BlueprintEvent)
// Parameters:
// class ABrickVehicle*                    Vehicle                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CL_ModHook_C::PostSpawnVehicle(class ABrickVehicle* Vehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CL_ModHook_C", "PostSpawnVehicle");

	Params::BP_CL_ModHook_C_PostSpawnVehicle Parms{};

	Parms.Vehicle = Vehicle;

	UObject::ProcessEvent(Func, &Parms);
}

}

