#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dumpster

#include "../../Include/SDK/Basic.hpp"

#include "../../Include/SDK/BP_Dumpster_classes.hpp"
#include "../../Include/SDK/BP_Dumpster_parameters.hpp"


namespace SDK
{

// Function BP_Dumpster.BP_Dumpster_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Dumpster_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dumpster_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

