#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FuelTank

#include "Basic.hpp"

#include "BP_FuelTank_classes.hpp"
#include "BP_FuelTank_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FuelTank.BP_FuelTank_C.ShouldSpawnLeakOnHit
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit_ShouldSpawnLeakOnHit                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// bool                                    ReturnValue_ShouldSpawnLeakOnHit                       (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_FuelTank_C::ShouldSpawnLeakOnHit(const struct FHitResult& Hit_ShouldSpawnLeakOnHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FuelTank_C", "ShouldSpawnLeakOnHit");

	Params::BP_FuelTank_C_ShouldSpawnLeakOnHit Parms{};

	Parms.Hit_ShouldSpawnLeakOnHit = std::move(Hit_ShouldSpawnLeakOnHit);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue_ShouldSpawnLeakOnHit;
}


SDK_NAMESPACE_END
