#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Industrial_Builder

#include "../../Include/SDK/Basic.hpp"

#include "../../Include/SDK/BP_Industrial_Builder_classes.hpp"
#include "../../Include/SDK/BP_Industrial_Builder_parameters.hpp"


namespace SDK
{

// Function BP_Industrial_Builder.BP_Industrial_Builder_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Industrial_Builder_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Industrial_Builder_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

