#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PowerPlant

#include "../../Include/SDK/Basic.hpp"

#include "../../Include/SDK/BP_PowerPlant_classes.hpp"
#include "../../Include/SDK/BP_PowerPlant_parameters.hpp"


namespace SDK
{

// Function BP_PowerPlant.BP_PowerPlant_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_PowerPlant_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PowerPlant_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

