#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Staircase

#include "../../Include/SDK/Basic.hpp"

#include "../../Include/SDK/BP_Staircase_classes.hpp"
#include "../../Include/SDK/BP_Staircase_parameters.hpp"


namespace SDK
{

// Function BP_Staircase.BP_Staircase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Staircase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Staircase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

