#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameOverlay

#include "Basic.hpp"

#include "WBP_GameOverlay_classes.hpp"
#include "WBP_GameOverlay_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_GameOverlay.WBP_GameOverlay_C.AddHUDNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_AddHUDNotification                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_AddHUDNotification                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddHUDNotification(class UHUDNotificationWidget* Widget_AddHUDNotification, int32 Index_AddHUDNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddHUDNotification");

	Params::WBP_GameOverlay_C_AddHUDNotification Parms{};

	Parms.Widget_AddHUDNotification = Widget_AddHUDNotification;
	Parms.Index_AddHUDNotification = Index_AddHUDNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateMoneyNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateMoneyNotification                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewAmount_UpdateMoneyNotification                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   AmountAdded_UpdateMoneyNotification                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateMoneyNotification(class UHUDNotificationWidget* Widget_UpdateMoneyNotification, float NewAmount_UpdateMoneyNotification, float AmountAdded_UpdateMoneyNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateMoneyNotification");

	Params::WBP_GameOverlay_C_UpdateMoneyNotification Parms{};

	Parms.Widget_UpdateMoneyNotification = Widget_UpdateMoneyNotification;
	Parms.NewAmount_UpdateMoneyNotification = NewAmount_UpdateMoneyNotification;
	Parms.AmountAdded_UpdateMoneyNotification = AmountAdded_UpdateMoneyNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateThumbnailNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateThumbnailNotification                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateThumbnailNotification(class UHUDNotificationWidget* Widget_UpdateThumbnailNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateThumbnailNotification");

	Params::WBP_GameOverlay_C_UpdateThumbnailNotification Parms{};

	Parms.Widget_UpdateThumbnailNotification = Widget_UpdateThumbnailNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddMatchTimerWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UMatchTimerWidget*                Widget_AddMatchTimerWidget                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddMatchTimerWidget(class UMatchTimerWidget* Widget_AddMatchTimerWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddMatchTimerWidget");

	Params::WBP_GameOverlay_C_AddMatchTimerWidget Parms{};

	Parms.Widget_AddMatchTimerWidget = Widget_AddMatchTimerWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateVehicleDownloadNotification
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateVehicleDownloadNotification               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      VehicleDisplayName_UpdateVehicleDownloadNotification   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   Progress_UpdateVehicleDownloadNotification             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateVehicleDownloadNotification(class UHUDNotificationWidget* Widget_UpdateVehicleDownloadNotification, const class FText& VehicleDisplayName_UpdateVehicleDownloadNotification, float Progress_UpdateVehicleDownloadNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateVehicleDownloadNotification");

	Params::WBP_GameOverlay_C_UpdateVehicleDownloadNotification Parms{};

	Parms.Widget_UpdateVehicleDownloadNotification = Widget_UpdateVehicleDownloadNotification;
	Parms.VehicleDisplayName_UpdateVehicleDownloadNotification = std::move(VehicleDisplayName_UpdateVehicleDownloadNotification);
	Parms.Progress_UpdateVehicleDownloadNotification = Progress_UpdateVehicleDownloadNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddInputHelpWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UInputHelpWidget*                 Widget_AddInputHelpWidget                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 InPosition_AddInputHelpWidget                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddInputHelpWidget(class UInputHelpWidget* Widget_AddInputHelpWidget, const struct FVector2D& InPosition_AddInputHelpWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddInputHelpWidget");

	Params::WBP_GameOverlay_C_AddInputHelpWidget Parms{};

	Parms.Widget_AddInputHelpWidget = Widget_AddInputHelpWidget;
	Parms.InPosition_AddInputHelpWidget = std::move(InPosition_AddInputHelpWidget);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddChatWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UChatWidget*                      Widget_AddChatWidget                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddChatWidget(class UChatWidget* Widget_AddChatWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddChatWidget");

	Params::WBP_GameOverlay_C_AddChatWidget Parms{};

	Parms.Widget_AddChatWidget = Widget_AddChatWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateSaveNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateSaveNotification                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bSuccess_UpdateSaveNotification                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsAutoSave_UpdateSaveNotification                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GameOverlay_C::UpdateSaveNotification(class UHUDNotificationWidget* Widget_UpdateSaveNotification, bool bSuccess_UpdateSaveNotification, bool bIsAutoSave_UpdateSaveNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateSaveNotification");

	Params::WBP_GameOverlay_C_UpdateSaveNotification Parms{};

	Parms.Widget_UpdateSaveNotification = Widget_UpdateSaveNotification;
	Parms.bSuccess_UpdateSaveNotification = bSuccess_UpdateSaveNotification;
	Parms.bIsAutoSave_UpdateSaveNotification = bIsAutoSave_UpdateSaveNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateCameraSpeedNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateCameraSpeedNotification                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewSpeedRatio_UpdateCameraSpeedNotification            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewMaxSpeed_UpdateCameraSpeedNotification              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateCameraSpeedNotification(class UHUDNotificationWidget* Widget_UpdateCameraSpeedNotification, float NewSpeedRatio_UpdateCameraSpeedNotification, float NewMaxSpeed_UpdateCameraSpeedNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateCameraSpeedNotification");

	Params::WBP_GameOverlay_C_UpdateCameraSpeedNotification Parms{};

	Parms.Widget_UpdateCameraSpeedNotification = Widget_UpdateCameraSpeedNotification;
	Parms.NewSpeedRatio_UpdateCameraSpeedNotification = NewSpeedRatio_UpdateCameraSpeedNotification;
	Parms.NewMaxSpeed_UpdateCameraSpeedNotification = NewMaxSpeed_UpdateCameraSpeedNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateCameraZoomNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateCameraZoomNotification                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewZoomRatio_UpdateCameraZoomNotification              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateCameraZoomNotification(class UHUDNotificationWidget* Widget_UpdateCameraZoomNotification, float NewZoomRatio_UpdateCameraZoomNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateCameraZoomNotification");

	Params::WBP_GameOverlay_C_UpdateCameraZoomNotification Parms{};

	Parms.Widget_UpdateCameraZoomNotification = Widget_UpdateCameraZoomNotification;
	Parms.NewZoomRatio_UpdateCameraZoomNotification = NewZoomRatio_UpdateCameraZoomNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddMatchStateWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UMatchStateWidget*                Widget_AddMatchStateWidget                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddMatchStateWidget(class UMatchStateWidget* Widget_AddMatchStateWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddMatchStateWidget");

	Params::WBP_GameOverlay_C_AddMatchStateWidget Parms{};

	Parms.Widget_AddMatchStateWidget = Widget_AddMatchStateWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddTeamScoreWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UTeamScoreWidget*                 Widget_AddTeamScoreWidget                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ETeamAttitude                           TeamAttitude_AddTeamScoreWidget                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddTeamScoreWidget(class UTeamScoreWidget* Widget_AddTeamScoreWidget, ETeamAttitude TeamAttitude_AddTeamScoreWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddTeamScoreWidget");

	Params::WBP_GameOverlay_C_AddTeamScoreWidget Parms{};

	Parms.Widget_AddTeamScoreWidget = Widget_AddTeamScoreWidget;
	Parms.TeamAttitude_AddTeamScoreWidget = TeamAttitude_AddTeamScoreWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateHUDVisibilityNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateHUDVisibilityNotification                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EHUDVisibility                          NewVisibility_UpdateHUDVisibilityNotification          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateHUDVisibilityNotification(class UHUDNotificationWidget* Widget_UpdateHUDVisibilityNotification, EHUDVisibility NewVisibility_UpdateHUDVisibilityNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateHUDVisibilityNotification");

	Params::WBP_GameOverlay_C_UpdateHUDVisibilityNotification Parms{};

	Parms.Widget_UpdateHUDVisibilityNotification = Widget_UpdateHUDVisibilityNotification;
	Parms.NewVisibility_UpdateHUDVisibilityNotification = NewVisibility_UpdateHUDVisibilityNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateCameraModeNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateCameraModeNotification                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ECameraMode                             NewMode_UpdateCameraModeNotification                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateCameraModeNotification(class UHUDNotificationWidget* Widget_UpdateCameraModeNotification, ECameraMode NewMode_UpdateCameraModeNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateCameraModeNotification");

	Params::WBP_GameOverlay_C_UpdateCameraModeNotification Parms{};

	Parms.Widget_UpdateCameraModeNotification = Widget_UpdateCameraModeNotification;
	Parms.NewMode_UpdateCameraModeNotification = NewMode_UpdateCameraModeNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateRestartFailedNotification
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateRestartFailedNotification                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      Message_UpdateRestartFailedNotification                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_GameOverlay_C::UpdateRestartFailedNotification(class UHUDNotificationWidget* Widget_UpdateRestartFailedNotification, const class FText& Message_UpdateRestartFailedNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateRestartFailedNotification");

	Params::WBP_GameOverlay_C_UpdateRestartFailedNotification Parms{};

	Parms.Widget_UpdateRestartFailedNotification = Widget_UpdateRestartFailedNotification;
	Parms.Message_UpdateRestartFailedNotification = std::move(Message_UpdateRestartFailedNotification);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateRespawnDelayNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateRespawnDelayNotification                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Remaining_UpdateRespawnDelayNotification               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateRespawnDelayNotification(class UHUDNotificationWidget* Widget_UpdateRespawnDelayNotification, float Remaining_UpdateRespawnDelayNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateRespawnDelayNotification");

	Params::WBP_GameOverlay_C_UpdateRespawnDelayNotification Parms{};

	Parms.Widget_UpdateRespawnDelayNotification = Widget_UpdateRespawnDelayNotification;
	Parms.Remaining_UpdateRespawnDelayNotification = Remaining_UpdateRespawnDelayNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateVehicleSeatNotification
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateVehicleSeatNotification                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      SeatDisplayName_UpdateVehicleSeatNotification          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_GameOverlay_C::UpdateVehicleSeatNotification(class UHUDNotificationWidget* Widget_UpdateVehicleSeatNotification, const class FText& SeatDisplayName_UpdateVehicleSeatNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateVehicleSeatNotification");

	Params::WBP_GameOverlay_C_UpdateVehicleSeatNotification Parms{};

	Parms.Widget_UpdateVehicleSeatNotification = Widget_UpdateVehicleSeatNotification;
	Parms.SeatDisplayName_UpdateVehicleSeatNotification = std::move(SeatDisplayName_UpdateVehicleSeatNotification);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateVehicleConstructionNotification
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateVehicleConstructionNotification           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      VehicleDisplayName_UpdateVehicleConstructionNotification(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   Progress_UpdateVehicleConstructionNotification         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::UpdateVehicleConstructionNotification(class UHUDNotificationWidget* Widget_UpdateVehicleConstructionNotification, const class FText& VehicleDisplayName_UpdateVehicleConstructionNotification, float Progress_UpdateVehicleConstructionNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateVehicleConstructionNotification");

	Params::WBP_GameOverlay_C_UpdateVehicleConstructionNotification Parms{};

	Parms.Widget_UpdateVehicleConstructionNotification = Widget_UpdateVehicleConstructionNotification;
	Parms.VehicleDisplayName_UpdateVehicleConstructionNotification = std::move(VehicleDisplayName_UpdateVehicleConstructionNotification);
	Parms.Progress_UpdateVehicleConstructionNotification = Progress_UpdateVehicleConstructionNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateInputTipsVisibility
// (BlueprintCallable, BlueprintEvent)

void UWBP_GameOverlay_C::UpdateInputTipsVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateInputTipsVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameOverlay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.OnHUDVisibilityChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const EHUDVisibility                    NewVisibility_OnHUDVisibilityChanged                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::OnHUDVisibilityChanged(const EHUDVisibility NewVisibility_OnHUDVisibilityChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "OnHUDVisibilityChanged");

	Params::WBP_GameOverlay_C_OnHUDVisibilityChanged Parms{};

	Parms.NewVisibility_OnHUDVisibilityChanged = NewVisibility_OnHUDVisibilityChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.RemoveInputTips
// (BlueprintCallable, BlueprintEvent)

void UWBP_GameOverlay_C::RemoveInputTips()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "RemoveInputTips");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameOverlay_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddCameraDashboardWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      InWidget_AddCameraDashboardWidget                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddCameraDashboardWidget(class UUserWidget* InWidget_AddCameraDashboardWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddCameraDashboardWidget");

	Params::WBP_GameOverlay_C_AddCameraDashboardWidget Parms{};

	Parms.InWidget_AddCameraDashboardWidget = InWidget_AddCameraDashboardWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.AddEditorDashboardWidget
// (BlueprintEvent)
// Parameters:
// class UUserWidget*                      InWidget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::AddEditorDashboardWidget(class UUserWidget* InWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "AddEditorDashboardWidget");

	Params::WBP_GameOverlay_C_AddEditorDashboardWidget Parms{};

	Parms.InWidget = InWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.UpdateVehicleCameraNotification
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UHUDNotificationWidget*           Widget_UpdateVehicleCameraNotification                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      CameraDisplayName_UpdateVehicleCameraNotification      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_GameOverlay_C::UpdateVehicleCameraNotification(class UHUDNotificationWidget* Widget_UpdateVehicleCameraNotification, const class FText& CameraDisplayName_UpdateVehicleCameraNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "UpdateVehicleCameraNotification");

	Params::WBP_GameOverlay_C_UpdateVehicleCameraNotification Parms{};

	Parms.Widget_UpdateVehicleCameraNotification = Widget_UpdateVehicleCameraNotification;
	Parms.CameraDisplayName_UpdateVehicleCameraNotification = std::move(CameraDisplayName_UpdateVehicleCameraNotification);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameOverlay.WBP_GameOverlay_C.ExecuteUbergraph_WBP_GameOverlay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameOverlay_C::ExecuteUbergraph_WBP_GameOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameOverlay_C", "ExecuteUbergraph_WBP_GameOverlay");

	Params::WBP_GameOverlay_C_ExecuteUbergraph_WBP_GameOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
