#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatMessage

#include "Basic.hpp"

#include "WBP_ChatMessage_classes.hpp"
#include "WBP_ChatMessage_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ChatMessage.WBP_ChatMessage_C.UpdateColorStyle
// (Event, Public, BlueprintEvent)
// Parameters:
// EBrickUIColorStyle                      NewColorStyle_UpdateColorStyle                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatMessage_C::UpdateColorStyle(EBrickUIColorStyle NewColorStyle_UpdateColorStyle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "UpdateColorStyle");

	Params::WBP_ChatMessage_C_UpdateColorStyle Parms{};

	Parms.NewColorStyle_UpdateColorStyle = NewColorStyle_UpdateColorStyle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.UpdateMessageText
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      NewText_UpdateMessageText                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ChatMessage_C::UpdateMessageText(const class FText& NewText_UpdateMessageText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "UpdateMessageText");

	Params::WBP_ChatMessage_C_UpdateMessageText Parms{};

	Parms.NewText_UpdateMessageText = std::move(NewText_UpdateMessageText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EBrickUIStyleState                      InContentStyleState                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatMessage_C::BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature");

	Params::WBP_ChatMessage_C_BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature Parms{};

	Parms.InColorStyle = InColorStyle;
	Parms.InContentStyleState = InContentStyleState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_ChatMessage_C::BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.ExecuteUbergraph_WBP_ChatMessage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatMessage_C::ExecuteUbergraph_WBP_ChatMessage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "ExecuteUbergraph_WBP_ChatMessage");

	Params::WBP_ChatMessage_C_ExecuteUbergraph_WBP_ChatMessage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
