#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CharacterDashboard

#include "Basic.hpp"

#include "WBP_CharacterDashboard_classes.hpp"
#include "WBP_CharacterDashboard_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.AddCharacterElements
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABrickPlayerController*           PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CharacterDashboard_C::AddCharacterElements(class ABrickPlayerController* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "AddCharacterElements");

	Params::WBP_CharacterDashboard_C_AddCharacterElements Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.AddCurrentItemElements
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_CharacterDashboard_C::AddCurrentItemElements()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "AddCurrentItemElements");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.SetHealth
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bCanBeDamaged                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CharacterDashboard_C::SetHealth(float Value, bool bCanBeDamaged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "SetHealth");

	Params::WBP_CharacterDashboard_C_SetHealth Parms{};

	Parms.Value = Value;
	Parms.bCanBeDamaged = bCanBeDamaged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.AddActionsAndSliders
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CharacterDashboard_C::AddActionsAndSliders()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "AddActionsAndSliders");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_Tick                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime_Tick                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CharacterDashboard_C::Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "Tick");

	Params::WBP_CharacterDashboard_C_Tick Parms{};

	Parms.MyGeometry_Tick = std::move(MyGeometry_Tick);
	Parms.InDeltaTime_Tick = InDeltaTime_Tick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.UpdateAmmo
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_CharacterDashboard_C::UpdateAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "UpdateAmmo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.PopulateDashboard
// (Event, Protected, BlueprintEvent)

void UWBP_CharacterDashboard_C::PopulateDashboard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "PopulateDashboard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CharacterDashboard.WBP_CharacterDashboard_C.ExecuteUbergraph_WBP_CharacterDashboard
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CharacterDashboard_C::ExecuteUbergraph_WBP_CharacterDashboard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CharacterDashboard_C", "ExecuteUbergraph_WBP_CharacterDashboard");

	Params::WBP_CharacterDashboard_C_ExecuteUbergraph_WBP_CharacterDashboard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
