#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUDNotification

#include "Basic.hpp"

#include "WBP_HUDNotification_classes.hpp"
#include "WBP_HUDNotification_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_HUDNotification.WBP_HUDNotification_C.PlayFadeInAnim
// (Event, Protected, BlueprintEvent)

void UWBP_HUDNotification_C::PlayFadeInAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "PlayFadeInAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.PlayFadeOutAnim
// (Event, Protected, BlueprintEvent)

void UWBP_HUDNotification_C::PlayFadeOutAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "PlayFadeOutAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.UpdateIsThumbnailNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewIsThumbnail_UpdateIsThumbnailNotification          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_HUDNotification_C::UpdateIsThumbnailNotification(bool bNewIsThumbnail_UpdateIsThumbnailNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "UpdateIsThumbnailNotification");

	Params::WBP_HUDNotification_C_UpdateIsThumbnailNotification Parms{};

	Parms.bNewIsThumbnail_UpdateIsThumbnailNotification = bNewIsThumbnail_UpdateIsThumbnailNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.InitializeNotification
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDisplayInfo&              InDisplayInfo_InitializeNotification                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
// const EBrickUIColorStyle                InColorStyle_InitializeNotification                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDNotification_C::InitializeNotification(const struct FDisplayInfo& InDisplayInfo_InitializeNotification, const EBrickUIColorStyle InColorStyle_InitializeNotification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "InitializeNotification");

	Params::WBP_HUDNotification_C_InitializeNotification Parms{};

	Parms.InDisplayInfo_InitializeNotification = std::move(InDisplayInfo_InitializeNotification);
	Parms.InColorStyle_InitializeNotification = InColorStyle_InitializeNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.ExecuteUbergraph_WBP_HUDNotification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDNotification_C::ExecuteUbergraph_WBP_HUDNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "ExecuteUbergraph_WBP_HUDNotification");

	Params::WBP_HUDNotification_C_ExecuteUbergraph_WBP_HUDNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
