#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlacableObject

#include "Basic.hpp"

#include "WBP_PlacableObject_classes.hpp"
#include "WBP_PlacableObject_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PlacableObject.WBP_PlacableObject_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_OnMouseButtonUp                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent_OnMouseButtonUp                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue_OnMouseButtonUp                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_PlacableObject_C::OnMouseButtonUp(const struct FGeometry& MyGeometry_OnMouseButtonUp, const struct FPointerEvent& MouseEvent_OnMouseButtonUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlacableObject_C", "OnMouseButtonUp");

	Params::WBP_PlacableObject_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry_OnMouseButtonUp = std::move(MyGeometry_OnMouseButtonUp);
	Parms.MouseEvent_OnMouseButtonUp = std::move(MouseEvent_OnMouseButtonUp);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.CallFunc_Handled_ReturnValue;
}


// Function WBP_PlacableObject.WBP_PlacableObject_C.UpdateIsFilterWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewIsFilter_UpdateIsFilterWidget                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_PlacableObject_C::UpdateIsFilterWidget(bool bNewIsFilter_UpdateIsFilterWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlacableObject_C", "UpdateIsFilterWidget");

	Params::WBP_PlacableObject_C_UpdateIsFilterWidget Parms{};

	Parms.bNewIsFilter_UpdateIsFilterWidget = bNewIsFilter_UpdateIsFilterWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PlacableObject.WBP_PlacableObject_C.ExecuteUbergraph_WBP_PlacableObject
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlacableObject_C::ExecuteUbergraph_WBP_PlacableObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlacableObject_C", "ExecuteUbergraph_WBP_PlacableObject");

	Params::WBP_PlacableObject_C_ExecuteUbergraph_WBP_PlacableObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
