#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Player

#include "Basic.hpp"

#include "WBP_Player_classes.hpp"
#include "WBP_Player_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Player.WBP_Player_C.AddRestrictedAreaWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class URestrictedAreaWidget*            InWidget_AddRestrictedAreaWidget                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::AddRestrictedAreaWidget(class URestrictedAreaWidget* InWidget_AddRestrictedAreaWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "AddRestrictedAreaWidget");

	Params::WBP_Player_C_AddRestrictedAreaWidget Parms{};

	Parms.InWidget_AddRestrictedAreaWidget = InWidget_AddRestrictedAreaWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Player.WBP_Player_C.AddCrosshairWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UCrosshairWidget*                 InWidget_AddCrosshairWidget                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::AddCrosshairWidget(class UCrosshairWidget* InWidget_AddCrosshairWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "AddCrosshairWidget");

	Params::WBP_Player_C_AddCrosshairWidget Parms{};

	Parms.InWidget_AddCrosshairWidget = InWidget_AddCrosshairWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Player.WBP_Player_C.AddCameraBrickWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UCameraBrickWidget*               InWidget_AddCameraBrickWidget                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::AddCameraBrickWidget(class UCameraBrickWidget* InWidget_AddCameraBrickWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "AddCameraBrickWidget");

	Params::WBP_Player_C_AddCameraBrickWidget Parms{};

	Parms.InWidget_AddCameraBrickWidget = InWidget_AddCameraBrickWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Player.WBP_Player_C.AddCharacterDashboardWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      InWidget_AddCharacterDashboardWidget                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::AddCharacterDashboardWidget(class UUserWidget* InWidget_AddCharacterDashboardWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "AddCharacterDashboardWidget");

	Params::WBP_Player_C_AddCharacterDashboardWidget Parms{};

	Parms.InWidget_AddCharacterDashboardWidget = InWidget_AddCharacterDashboardWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Player.WBP_Player_C.AddVehicleDashboardWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      InWidget_AddVehicleDashboardWidget                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::AddVehicleDashboardWidget(class UUserWidget* InWidget_AddVehicleDashboardWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "AddVehicleDashboardWidget");

	Params::WBP_Player_C_AddVehicleDashboardWidget Parms{};

	Parms.InWidget_AddVehicleDashboardWidget = InWidget_AddVehicleDashboardWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Player.WBP_Player_C.ExecuteUbergraph_WBP_Player
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Player_C::ExecuteUbergraph_WBP_Player(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Player_C", "ExecuteUbergraph_WBP_Player");

	Params::WBP_Player_C_ExecuteUbergraph_WBP_Player Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
