#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TeamScore

#include "Basic.hpp"

#include "WBP_TeamScore_classes.hpp"
#include "WBP_TeamScore_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_TeamScore.WBP_TeamScore_C.UpdateScore
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NewScore_UpdateScore                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewMaxScore_UpdateScore                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TeamScore_C::UpdateScore(int32 NewScore_UpdateScore, int32 NewMaxScore_UpdateScore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TeamScore_C", "UpdateScore");

	Params::WBP_TeamScore_C_UpdateScore Parms{};

	Parms.NewScore_UpdateScore = NewScore_UpdateScore;
	Parms.NewMaxScore_UpdateScore = NewMaxScore_UpdateScore;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TeamScore.WBP_TeamScore_C.UpdateTeamAttitude
// (Event, Protected, BlueprintEvent)
// Parameters:
// ETeamAttitude                           NewTeamAttitude_UpdateTeamAttitude                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TeamScore_C::UpdateTeamAttitude(ETeamAttitude NewTeamAttitude_UpdateTeamAttitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TeamScore_C", "UpdateTeamAttitude");

	Params::WBP_TeamScore_C_UpdateTeamAttitude Parms{};

	Parms.NewTeamAttitude_UpdateTeamAttitude = NewTeamAttitude_UpdateTeamAttitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TeamScore.WBP_TeamScore_C.UpdateTeamIcon
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UTexture2D*                       NewIcon_UpdateTeamIcon                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TeamScore_C::UpdateTeamIcon(class UTexture2D* NewIcon_UpdateTeamIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TeamScore_C", "UpdateTeamIcon");

	Params::WBP_TeamScore_C_UpdateTeamIcon Parms{};

	Parms.NewIcon_UpdateTeamIcon = NewIcon_UpdateTeamIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TeamScore.WBP_TeamScore_C.ExecuteUbergraph_WBP_TeamScore
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TeamScore_C::ExecuteUbergraph_WBP_TeamScore(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TeamScore_C", "ExecuteUbergraph_WBP_TeamScore");

	Params::WBP_TeamScore_C_ExecuteUbergraph_WBP_TeamScore Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
