#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MatchState

#include "Basic.hpp"

#include "WBP_MatchState_classes.hpp"
#include "WBP_MatchState_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MatchState.WBP_MatchState_C.UpdateMatchState
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      NewDisplayText_UpdateMatchState                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// EBrickUIColorStyle                      NewColorStyle_UpdateMatchState                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFadeOut_UpdateMatchState                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MatchState_C::UpdateMatchState(const class FText& NewDisplayText_UpdateMatchState, EBrickUIColorStyle NewColorStyle_UpdateMatchState, bool bFadeOut_UpdateMatchState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchState_C", "UpdateMatchState");

	Params::WBP_MatchState_C_UpdateMatchState Parms{};

	Parms.NewDisplayText_UpdateMatchState = std::move(NewDisplayText_UpdateMatchState);
	Parms.NewColorStyle_UpdateMatchState = NewColorStyle_UpdateMatchState;
	Parms.bFadeOut_UpdateMatchState = bFadeOut_UpdateMatchState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MatchState.WBP_MatchState_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// const class UWidgetAnimation*           Animation_OnAnimationFinished                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchState_C::OnAnimationFinished(const class UWidgetAnimation* Animation_OnAnimationFinished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchState_C", "OnAnimationFinished");

	Params::WBP_MatchState_C_OnAnimationFinished Parms{};

	Parms.Animation_OnAnimationFinished = Animation_OnAnimationFinished;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MatchState.WBP_MatchState_C.ExecuteUbergraph_WBP_MatchState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchState_C::ExecuteUbergraph_WBP_MatchState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchState_C", "ExecuteUbergraph_WBP_MatchState");

	Params::WBP_MatchState_C_ExecuteUbergraph_WBP_MatchState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
