#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatMessage

#include "Basic.hpp"

#include "WBP_ChatMessage_classes.hpp"
#include "WBP_ChatMessage_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ChatMessage.WBP_ChatMessage_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_OnMouseButtonDown                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent_OnMouseButtonDown                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue_OnMouseButtonDown                          (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_ChatMessage_C::OnMouseButtonDown(const struct FGeometry& MyGeometry_OnMouseButtonDown, const struct FPointerEvent& MouseEvent_OnMouseButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "OnMouseButtonDown");

	Params::WBP_ChatMessage_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry_OnMouseButtonDown = std::move(MyGeometry_OnMouseButtonDown);
	Parms.MouseEvent_OnMouseButtonDown = std::move(MouseEvent_OnMouseButtonDown);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.CallFunc_Handled_ReturnValue;
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_OnMouseButtonUp                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent_OnMouseButtonUp                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue_OnMouseButtonUp                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_ChatMessage_C::OnMouseButtonUp(const struct FGeometry& MyGeometry_OnMouseButtonUp, const struct FPointerEvent& MouseEvent_OnMouseButtonUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "OnMouseButtonUp");

	Params::WBP_ChatMessage_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry_OnMouseButtonUp = std::move(MyGeometry_OnMouseButtonUp);
	Parms.MouseEvent_OnMouseButtonUp = std::move(MouseEvent_OnMouseButtonUp);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.CallFunc_Handled_ReturnValue;
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_ChatMessage_C::BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "BndEvt__WBP_ChatMessage_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.InitializeChatMessage
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      NewText_InitializeChatMessage                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const EBrickUIColorStyle                NewColorStyle_InitializeChatMessage                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const bool                              bInIsChatFocused_InitializeChatMessage                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const bool                              bWasJustReceived_InitializeChatMessage                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ChatMessage_C::InitializeChatMessage(const class FText& NewText_InitializeChatMessage, const EBrickUIColorStyle NewColorStyle_InitializeChatMessage, const bool bInIsChatFocused_InitializeChatMessage, const bool bWasJustReceived_InitializeChatMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "InitializeChatMessage");

	Params::WBP_ChatMessage_C_InitializeChatMessage Parms{};

	Parms.NewText_InitializeChatMessage = std::move(NewText_InitializeChatMessage);
	Parms.NewColorStyle_InitializeChatMessage = NewColorStyle_InitializeChatMessage;
	Parms.bInIsChatFocused_InitializeChatMessage = bInIsChatFocused_InitializeChatMessage;
	Parms.bWasJustReceived_InitializeChatMessage = bWasJustReceived_InitializeChatMessage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.SetFocusedState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewFocused                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ChatMessage_C::SetFocusedState(bool bNewFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "SetFocusedState");

	Params::WBP_ChatMessage_C_SetFocusedState Parms{};

	Parms.bNewFocused = bNewFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.UpdateChatFocused
// (Event, Public, BlueprintEvent)
// Parameters:
// const bool                              bInIsChatFocused_UpdateChatFocused                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ChatMessage_C::UpdateChatFocused(const bool bInIsChatFocused_UpdateChatFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "UpdateChatFocused");

	Params::WBP_ChatMessage_C_UpdateChatFocused Parms{};

	Parms.bInIsChatFocused_UpdateChatFocused = bInIsChatFocused_UpdateChatFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_Tick                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime_Tick                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatMessage_C::Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "Tick");

	Params::WBP_ChatMessage_C_Tick Parms{};

	Parms.MyGeometry_Tick = std::move(MyGeometry_Tick);
	Parms.InDeltaTime_Tick = InDeltaTime_Tick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatMessage.WBP_ChatMessage_C.ExecuteUbergraph_WBP_ChatMessage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatMessage_C::ExecuteUbergraph_WBP_ChatMessage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatMessage_C", "ExecuteUbergraph_WBP_ChatMessage");

	Params::WBP_ChatMessage_C_ExecuteUbergraph_WBP_ChatMessage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
