#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Interaction

#include "Basic.hpp"

#include "WBP_Interaction_classes.hpp"
#include "WBP_Interaction_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Interaction.WBP_Interaction_C.AddOptionWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UInteractionOptionWidget*         Widget_AddOptionWidget                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex_AddOptionWidget                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Interaction_C::AddOptionWidget(class UInteractionOptionWidget* Widget_AddOptionWidget, int32 OptionIndex_AddOptionWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Interaction_C", "AddOptionWidget");

	Params::WBP_Interaction_C_AddOptionWidget Parms{};

	Parms.Widget_AddOptionWidget = Widget_AddOptionWidget;
	Parms.OptionIndex_AddOptionWidget = OptionIndex_AddOptionWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Interaction.WBP_Interaction_C.ExecuteUbergraph_WBP_Interaction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Interaction_C::ExecuteUbergraph_WBP_Interaction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Interaction_C", "ExecuteUbergraph_WBP_Interaction");

	Params::WBP_Interaction_C_ExecuteUbergraph_WBP_Interaction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
