#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickDataSingleton

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_BrickDataSingleton.BP_BrickDataSingleton_C.GetAmmoTypeDisplayInfo
// 0x0260 (0x0260 - 0x0000)
struct BP_BrickDataSingleton_C_GetAmmoTypeDisplayInfo final
{
public:
	EAmmoType                                     AmmoType;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDisplayInfo                           OutDisplayInfo;                                    // 0x0008(0x0040)(Parm, OutParm)
	EBrickUIColorStyle                            OutColorStyle;                                     // 0x0048(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0049(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	EAmmoType                                     Temp_byte_Variable;                                // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDisplayInfo                           Temp_struct_Variable;                              // 0x0050(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo;                     // 0x0090(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo_1;                   // 0x00D0(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo_2;                   // 0x0110(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo_3;                   // 0x0150(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo_4;                   // 0x0190(0x0040)()
	struct FDisplayInfo                           K2Node_MakeStruct_DisplayInfo_5;                   // 0x01D0(0x0040)()
	EAmmoType                                     Temp_byte_Variable_1;                              // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_211[0x7];                                      // 0x0211(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDisplayInfo                           K2Node_Select_Default;                             // 0x0218(0x0040)()
	EBrickUIColorStyle                            Temp_byte_Variable_2;                              // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_3;                              // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_4;                              // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_5;                              // 0x025B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_6;                              // 0x025C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_7;                              // 0x025D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_8;                              // 0x025E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            K2Node_Select_Default_1;                           // 0x025F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BrickDataSingleton_C_GetAmmoTypeDisplayInfo;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
