#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConquestGameMode

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ConquestGameMode.BP_ConquestGameMode_C
// 0x0008 (0x0460 - 0x0458)
class ABP_ConquestGameMode_C final : public AConquestGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ConquestGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ConquestGameMode_C")
	}
	static class ABP_ConquestGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ConquestGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_ConquestGameMode_C;

SDK_NAMESPACE_END
