#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeathmatchGameMode

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DeathmatchGameMode.BP_DeathmatchGameMode_C
// 0x0008 (0x0450 - 0x0448)
class ABP_DeathmatchGameMode_C final : public ADeathmatchGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DeathmatchGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DeathmatchGameMode_C")
	}
	static class ABP_DeathmatchGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DeathmatchGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_DeathmatchGameMode_C;

SDK_NAMESPACE_END
