#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Kick_Sequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_RC_Sequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Kick_Sequence.BP_Kick_Sequence_C
// 0x0028 (0x02C0 - 0x0298)
class ABP_Kick_Sequence_C final : public ABP_RC_Sequence_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Kick_Sequence_C;                 // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextRenderComponent*                   TextRender;                                        // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Runner;                                            // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TextTimeline_Height_6E6C29D64FB81D64993200A2DCA8B17F; // 0x02B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TextTimeline__Direction_6E6C29D64FB81D64993200A2DCA8B17F; // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B5[0x3];                                      // 0x02B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TextTimeline;                                      // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Kick_Sequence(int32 EntryPoint);
	void ReceiveBeginPlay();
	void TextTimeline__UpdateFunc();
	void TextTimeline__FinishedFunc();

	struct FVector GetLookAtTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Kick_Sequence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Kick_Sequence_C")
	}
	static class ABP_Kick_Sequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Kick_Sequence_C>();
	}
};
DUMPER7_ASSERTS_ABP_Kick_Sequence_C;

SDK_NAMESPACE_END
