#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZombieGameMode

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ZombieGameMode.BP_ZombieGameMode_C
// 0x0008 (0x0490 - 0x0488)
class ABP_ZombieGameMode_C final : public AZombieGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ZombieGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ZombieGameMode_C")
	}
	static class ABP_ZombieGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ZombieGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_ZombieGameMode_C;

SDK_NAMESPACE_END
