#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPML_Utilities

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPML_Utilities.BPML_Utilities_C
// 0x0000 (0x0028 - 0x0028)
class UBPML_Utilities_C final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPML_Utilities_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPML_Utilities_C")
	}
	static class UBPML_Utilities_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPML_Utilities_C>();
	}
};
DUMPER7_ASSERTS_UBPML_Utilities_C;

SDK_NAMESPACE_END
