#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TimespanProperty

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TimespanProperty.WBP_TimespanProperty_C
// 0x0040 (0x02C0 - 0x0280)
class UWBP_TimespanProperty_C final : public UTimespanPropertyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickComboBox_C*                   ComboBox;                                          // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BrickSlider_C*                     Slider;                                            // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FTimespan                              CurrentValue;                                      // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              MinValue;                                          // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              MaxValue;                                          // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              LastValue;                                         // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         LastComboBoxValue;                                 // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_TimespanProperty(int32 EntryPoint);
	void BndEvt__WBP_TimespanProperty_ComboBox_K2Node_ComponentBoundEvent_0_OnItemSelected__DelegateSignature(int32 Item, EValueChangedEventType EventType);
	void BndEvt__WBP_TimespanProperty_SecondsSlider_K2Node_ComponentBoundEvent_2_OnSliderValueChanged__DelegateSignature(float Value, EValueChangedEventType EventType);
	void UpdateTimespanProperty(const bool bInit, const struct FTimespan& Timespan, const struct FTimespan& MinValue_0, const struct FTimespan& MaxValue_0, const bool bAllowInfinite);
	void On_ComboBox_InitializeItemDelegate_0(int32 Item, struct FBrickComboBoxItemParams* OutParams);
	void InitComboBoxValue(struct FTimespan& InTimespan);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TimespanProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TimespanProperty_C")
	}
	static class UWBP_TimespanProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TimespanProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TimespanProperty_C;

SDK_NAMESPACE_END
