#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ObjectProperty

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ObjectProperty.WBP_ObjectProperty_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_ObjectProperty_C final : public UObjectPropertyWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ObjectProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ObjectProperty_C")
	}
	static class UWBP_ObjectProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ObjectProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ObjectProperty_C;

SDK_NAMESPACE_END
