#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComboBoxFadingPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ComboBoxFadingPanel.WBP_ComboBoxFadingPanel_C
// 0x0010 (0x0298 - 0x0288)
class UWBP_ComboBoxFadingPanel_C final : public UFadingPanelWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_0;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ComboBoxFadingPanel(int32 EntryPoint);
	void UpdateFadeAnimation(float FadeAmount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ComboBoxFadingPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ComboBoxFadingPanel_C")
	}
	static class UWBP_ComboBoxFadingPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ComboBoxFadingPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ComboBoxFadingPanel_C;

SDK_NAMESPACE_END
