#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickCheckBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickCheckBox.WBP_BrickCheckBox_C
// 0x0030 (0x02C8 - 0x0298)
class UWBP_BrickCheckBox_C final : public UButtonWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           FillBorder;                                        // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        TextBlock;                                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bIsChecked;                                        // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool bNewChecked)> OnIsCheckedChanged;                             // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_WBP_BrickCheckBox(int32 EntryPoint);
	void OnClicked();
	void UpdateButtonStyle(const EBrickUIColorStyle NewColorStyle, const EBrickUIBrushState NewBrushState);
	void Construct();
	void UpdateIsChecked();
	void SetIsChecked(bool bNewChecked);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickCheckBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickCheckBox_C")
	}
	static class UWBP_BrickCheckBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickCheckBox_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickCheckBox_C;

SDK_NAMESPACE_END
