#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuButton

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MenuButton.WBP_MenuButton_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_MenuButton_C final : public UMenuButtonWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MenuButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MenuButton_C")
	}
	static class UWBP_MenuButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MenuButton_C;

SDK_NAMESPACE_END
