#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FlashSequenceProperty

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FlashSequenceProperty.WBP_FlashSequenceProperty_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_FlashSequenceProperty_C final : public UFlashSequencePropertyWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FlashSequenceProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FlashSequenceProperty_C")
	}
	static class UWBP_FlashSequenceProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FlashSequenceProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FlashSequenceProperty_C;

SDK_NAMESPACE_END
