#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuNews

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "SlateCore_structs.hpp"
#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MenuNews.WBP_MenuNews_C.ExecuteUbergraph_WBP_MenuNews
// 0x0210 (0x0210 - 0x0000)
struct WBP_MenuNews_C_ExecuteUbergraph_WBP_MenuNews final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBrLatestNewsDetails                   K2Node_CustomEvent_News_1;                         // 0x0008(0x0038)(ConstParm)
	class FString                                 K2Node_CustomEvent_ErrorMessage_1;                 // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_HttpStatusCode_1;               // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FBrLatestNewsDetails& News, const class FString& ErrorMessage, int32 HttpStatusCode)> K2Node_CreateDelegate_OutputDelegate; // 0x0054(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBrLatestNewsDetails                   K2Node_CustomEvent_News;                           // 0x0068(0x0038)(ConstParm)
	class FString                                 K2Node_CustomEvent_ErrorMessage;                   // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_HttpStatusCode;                 // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FBrLatestNewsDetails& News, const class FString& ErrorMessage, int32 HttpStatusCode)> K2Node_CreateDelegate_OutputDelegate_1; // 0x00B4(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable;                              // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FBrLatestNewsDetails                   Temp_struct_Variable;                              // 0x00D8(0x0038)()
	class UBrQueryLatestNewsAsyncAction*          CallFunc_QueryLatestNews_ReturnValue;              // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_AsDate_DateTime_ReturnValue;              // 0x0120(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0138(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0178(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0190(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x01A8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01E8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01F8(0x0018)()
};
DUMPER7_ASSERTS_WBP_MenuNews_C_ExecuteUbergraph_WBP_MenuNews;

// Function WBP_MenuNews.WBP_MenuNews_C.OnSuccess_525CB4C942788D6D9EDF80BF367842CA
// 0x0050 (0x0050 - 0x0000)
struct WBP_MenuNews_C_OnSuccess_525CB4C942788D6D9EDF80BF367842CA final
{
public:
	struct FBrLatestNewsDetails                   News;                                              // 0x0000(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FString                                 ErrorMessage;                                      // 0x0038(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         HttpStatusCode;                                    // 0x0048(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuNews_C_OnSuccess_525CB4C942788D6D9EDF80BF367842CA;

// Function WBP_MenuNews.WBP_MenuNews_C.OnFailure_525CB4C942788D6D9EDF80BF367842CA
// 0x0050 (0x0050 - 0x0000)
struct WBP_MenuNews_C_OnFailure_525CB4C942788D6D9EDF80BF367842CA final
{
public:
	struct FBrLatestNewsDetails                   News;                                              // 0x0000(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FString                                 ErrorMessage;                                      // 0x0038(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         HttpStatusCode;                                    // 0x0048(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuNews_C_OnFailure_525CB4C942788D6D9EDF80BF367842CA;

// Function WBP_MenuNews.WBP_MenuNews_C.OpenNewsArticle
// 0x0008 (0x0008 - 0x0000)
struct WBP_MenuNews_C_OpenNewsArticle final
{
public:
	class UBrickGameInstance*                     CallFunc_Get_ReturnValue;                          // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuNews_C_OpenNewsArticle;

// Function WBP_MenuNews.WBP_MenuNews_C.OnMouseButtonUp
// 0x02F0 (0x02F0 - 0x0000)
struct WBP_MenuNews_C_OnMouseButtonUp final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x00A8(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0160(0x00B8)()
	struct FKey                                   CallFunc_PointerEvent_GetEffectingButton_ReturnValue; // 0x0218(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0238(0x00B8)()
};
DUMPER7_ASSERTS_WBP_MenuNews_C_OnMouseButtonUp;

// Function WBP_MenuNews.WBP_MenuNews_C.OnMouseButtonDown
// 0x02F0 (0x02F0 - 0x0000)
struct WBP_MenuNews_C_OnMouseButtonDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x00A8(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0160(0x00B8)()
	struct FKey                                   CallFunc_PointerEvent_GetEffectingButton_ReturnValue; // 0x0218(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0238(0x00B8)()
};
DUMPER7_ASSERTS_WBP_MenuNews_C_OnMouseButtonDown;

// Function WBP_MenuNews.WBP_MenuNews_C.UpdatePreviewImage
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_MenuNews_C_UpdatePreviewImage final
{
public:
	struct FBrickThumbnailRequest                 K2Node_MakeStruct_BrickThumbnailRequest;           // 0x0000(0x0098)()
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_MenuNews_C_UpdatePreviewImage;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
