#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCBrowser

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"
#include "Engine_structs.hpp"
#include "FluUGC_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.ExecuteUbergraph_WBP_UGCBrowser
// 0x0630 (0x0630 - 0x0000)
struct WBP_UGCBrowser_C_ExecuteUbergraph_WBP_UGCBrowser final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0044(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0054(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0064(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0074(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0084(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x0094(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_10;           // 0x00A4(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_11;           // 0x00B4(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x00C8(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x00E0(0x0018)()
	bool                                          Temp_bool_Variable_1;                              // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIColorStyle                            Temp_byte_Variable;                                // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_1;                              // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x00FC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x010C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIColorStyle                            Temp_byte_Variable_2;                              // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_3;                              // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFluUGCItemVote                               Temp_byte_Variable_4;                              // 0x011F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_5;                              // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_6;                              // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            Temp_byte_Variable_7;                              // 0x0122(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFluUGCItemVote                               Temp_byte_Variable_8;                              // 0x0123(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_124[0x4];                                      // 0x0124(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_2;                              // 0x0128(0x0018)()
	class FText                                   Temp_text_Variable_3;                              // 0x0140(0x0018)()
	class FText                                   Temp_text_Variable_4;                              // 0x0158(0x0018)()
	EFluUGCItemVote                               Temp_byte_Variable_9;                              // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFluUGCItemVote                               Temp_byte_Variable_10;                             // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_172[0x2];                                      // 0x0172(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_14;           // 0x0174(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable;                          // 0x0188(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable_1;                        // 0x01B0(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable_2;                        // 0x01D8(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_4;                              // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable_3;                        // 0x0208(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable_4;                        // 0x0230(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsArrayProperty_1;                   // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsFavorited;                         // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bCanReplaceCurrent;                   // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bCanSpawn;                            // 0x025B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_SpawnFailureText;                     // 0x0260(0x0018)(ConstParm)
	bool                                          K2Node_Event_bIsSubscribed;                        // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIColorStyle                            K2Node_Select_Default;                             // 0x0279(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFluUGCItemVote                               K2Node_Event_Vote;                                 // 0x027A(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27B[0x5];                                      // 0x027B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue;               // 0x0280(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            K2Node_Select_Default_1;                           // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_289[0x7];                                      // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_2;                           // 0x0290(0x0018)()
	TDelegate<void()>                             K2Node_Select_Default_3;                           // 0x02A8(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	TSoftObjectPtr<class UTexture2D>              K2Node_Select_Default_4;                           // 0x02B8(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_1;             // 0x02E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_15;           // 0x02E8(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_2;             // 0x02F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue;                 // 0x0300(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_16;           // 0x0308(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_1;               // 0x0318(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_17;           // 0x0320(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_3;             // 0x0330(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_18;           // 0x0338(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_2;               // 0x0348(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_3;               // 0x0350(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_4;             // 0x0358(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_5;             // 0x0360(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_4;               // 0x0368(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_5;               // 0x0370(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_6;               // 0x0378(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_6;             // 0x0380(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_19;           // 0x0388(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_7;             // 0x0398(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateViewInBrowserButton_ReturnValue;    // 0x03A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_7;               // 0x03A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_8;             // 0x03B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_9;             // 0x03B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_8;               // 0x03C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_9;               // 0x03C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_10;            // 0x03D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateExitButton_ReturnValue;             // 0x03D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_11;            // 0x03E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_20;           // 0x03E8(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonWidget*                      CallFunc_CreateImportButton_ReturnValue;           // 0x03F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_12;            // 0x0400(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_21;           // 0x0408(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_10;              // 0x0418(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_13;            // 0x0420(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_14;            // 0x0428(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_15;            // 0x0430(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_11;              // 0x0438(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_12;              // 0x0440(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_16;            // 0x0448(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_13;              // 0x0450(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_17;            // 0x0458(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0460(0x0018)()
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_14;              // 0x0478(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_15;              // 0x0480(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_18;            // 0x0488(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_22;           // 0x0490(0x0010)(ZeroConstructor, NoDestructor)
	class FText                                   K2Node_Event_CurrentInvincibilityText;             // 0x04A0(0x0018)(ConstParm)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_16;              // 0x04B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x04C0(0x0040)(HasGetValueTypeHash)
	class UMenuButtonPanelWidget*                 CallFunc_GetButtonPanel_ReturnValue_19;            // 0x0500(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0508(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_23;           // 0x0520(0x0010)(ZeroConstructor, NoDestructor)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0530(0x0040)(HasGetValueTypeHash)
	TDelegate<void(struct FTooltipContent* OutContent)> K2Node_CreateDelegate_OutputDelegate_24;     // 0x0570(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0580(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0590(0x0018)()
	bool                                          K2Node_Event_bIsArrayProperty;                     // 0x05A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsSelected;                          // 0x05A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5AA[0x6];                                      // 0x05AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_17;              // 0x05B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select_Default_5;                           // 0x05B8(0x0018)()
	TDelegate<void()>                             K2Node_Select_Default_6;                           // 0x05D0(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	EBrickUIColorStyle                            K2Node_Select_Default_7;                           // 0x05E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E1[0x3];                                      // 0x05E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_25;           // 0x05E4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_5F4[0x4];                                      // 0x05F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              K2Node_Select_Default_8;                           // 0x05F8(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_18;              // 0x0620(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue_19;              // 0x0628(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_ExecuteUbergraph_WBP_UGCBrowser;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateAddOrRemoveItemButton
// 0x0002 (0x0002 - 0x0000)
struct WBP_UGCBrowser_C_CreateAddOrRemoveItemButton final
{
public:
	bool                                          bIsArrayProperty;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bIsSelected;                                       // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateAddOrRemoveItemButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateSpawnInvincibilityButton
// 0x0018 (0x0018 - 0x0000)
struct WBP_UGCBrowser_C_CreateSpawnInvincibilityButton final
{
public:
	class FText                                   CurrentInvincibilityText;                          // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateSpawnInvincibilityButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateVoteButtons
// 0x0001 (0x0001 - 0x0000)
struct WBP_UGCBrowser_C_CreateVoteButtons final
{
public:
	EFluUGCItemVote                               Vote;                                              // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateVoteButtons;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateSubscribeButton
// 0x0001 (0x0001 - 0x0000)
struct WBP_UGCBrowser_C_CreateSubscribeButton final
{
public:
	bool                                          bIsSubscribed;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateSubscribeButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateSpawnButton
// 0x0020 (0x0020 - 0x0000)
struct WBP_UGCBrowser_C_CreateSpawnButton final
{
public:
	bool                                          bCanReplaceCurrent;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bCanSpawn;                                         // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   SpawnFailureText;                                  // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateSpawnButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateFavoriteButton
// 0x0001 (0x0001 - 0x0000)
struct WBP_UGCBrowser_C_CreateFavoriteButton final
{
public:
	bool                                          bIsFavorited;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateFavoriteButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.CreateClearItemsButton
// 0x0001 (0x0001 - 0x0000)
struct WBP_UGCBrowser_C_CreateClearItemsButton final
{
public:
	bool                                          bIsArrayProperty;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_CreateClearItemsButton;

// Function WBP_UGCBrowser.WBP_UGCBrowser_C.GetSpawnButtonTooltipContent
// 0x0088 (0x0088 - 0x0000)
struct WBP_UGCBrowser_C_GetSpawnButtonTooltipContent final
{
public:
	struct FTooltipContent                        OutContent;                                        // 0x0000(0x0040)(Parm, OutParm)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTooltipContent                        K2Node_MakeStruct_TooltipContent;                  // 0x0048(0x0040)()
};
DUMPER7_ASSERTS_WBP_UGCBrowser_C_GetSpawnButtonTooltipContent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
