#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Inventory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Inventory.WBP_Inventory_C
// 0x0010 (0x0298 - 0x0288)
class UWBP_Inventory_C final : public UInventoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickVerticalBox*                      BrickVerticalBox_27;                               // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Inventory(int32 EntryPoint);
	void AddCategoryWidget(class UInventoryCategoryWidget* InWidget, const int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Inventory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Inventory_C")
	}
	static class UWBP_Inventory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Inventory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Inventory_C;

SDK_NAMESPACE_END
