#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FlashSequenceItemWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FlashSequenceItemWidget.WBP_FlashSequenceItemWidget_C
// 0x0008 (0x02E0 - 0x02D8)
class UWBP_FlashSequenceItemWidget_C final : public UFlashSequenceItemWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_FlashSequenceItemWidget(int32 EntryPoint);
	void UpdateIsLit(bool bNewLit);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FlashSequenceItemWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FlashSequenceItemWidget_C")
	}
	static class UWBP_FlashSequenceItemWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FlashSequenceItemWidget_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FlashSequenceItemWidget_C;

SDK_NAMESPACE_END
