#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickEditor_BottomDashboard

#include "Basic.hpp"

#include "WBP_Dashboard_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickEditor_BottomDashboard.WBP_BrickEditor_BottomDashboard_C
// 0x0010 (0x0330 - 0x0320)
class UWBP_BrickEditor_BottomDashboard_C final : public UWBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_BrickEditor_BottomDashboard_C;  // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickEditorMode*                       BrickEditorMode;                                   // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddMirrorModeAndViewModeActions();
	void PopulateDashboard();
	void SetBrickEditorMode(class UBrickEditorMode* NewBrickEditorMode);
	void Destruct();
	void OnBrickEditorModeChanged(class UBrickEditorMode* NewBrickEditorMode);
	void ExecuteUbergraph_WBP_BrickEditor_BottomDashboard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickEditor_BottomDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickEditor_BottomDashboard_C")
	}
	static class UWBP_BrickEditor_BottomDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickEditor_BottomDashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickEditor_BottomDashboard_C;

SDK_NAMESPACE_END
