#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Player

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Player.WBP_Player_C
// 0x0010 (0x0540 - 0x0530)
class UWBP_Player_C final : public UPlayerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0530(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AddRestrictedAreaWidget(class URestrictedAreaWidget* InWidget_AddRestrictedAreaWidget);
	void AddCrosshairWidget(class UCrosshairWidget* InWidget_AddCrosshairWidget);
	void AddCameraBrickWidget(class UCameraBrickWidget* InWidget_AddCameraBrickWidget);
	void AddCharacterDashboardWidget(class UUserWidget* InWidget_AddCharacterDashboardWidget);
	void AddVehicleDashboardWidget(class UUserWidget* InWidget_AddVehicleDashboardWidget);
	void ExecuteUbergraph_WBP_Player(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Player_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Player_C")
	}
	static class UWBP_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Player_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Player_C;

SDK_NAMESPACE_END
