#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickComboBoxCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickComboBoxCategory.WBP_BrickComboBoxCategory_C
// 0x0010 (0x0270 - 0x0260)
class UWBP_BrickComboBoxCategory_C final : public UBrickComboBoxCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickTextBlock*                        BrickTextBlock_0;                                  // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BrickComboBoxCategory(int32 EntryPoint);
	void InitializeCategory(const class FText& InCategoryName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickComboBoxCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickComboBoxCategory_C")
	}
	static class UWBP_BrickComboBoxCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickComboBoxCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickComboBoxCategory_C;

SDK_NAMESPACE_END
