#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputHelpCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputHelpCategory.WBP_InputHelpCategory_C
// 0x0030 (0x0290 - 0x0260)
class UWBP_InputHelpCategory_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickButton_C*                     Button;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            IconImage;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        TextBlock;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInputCategory*                         Category;                                          // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsPartOfInputHelp;                                // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void BndEvt__WBP_InputHelpCategory_Button_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void SetInputCategory(class UInputCategory* InCategory);
	void RecycleObject();
	void ExecuteUbergraph_WBP_InputHelpCategory(int32 EntryPoint);

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputHelpCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputHelpCategory_C")
	}
	static class UWBP_InputHelpCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputHelpCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputHelpCategory_C;

SDK_NAMESPACE_END
