#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KickedPlayer

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_KickedPlayer.WBP_KickedPlayer_C
// 0x0000 (0x0310 - 0x0310)
class UWBP_KickedPlayer_C final : public UKickedPlayerWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_KickedPlayer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_KickedPlayer_C")
	}
	static class UWBP_KickedPlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_KickedPlayer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_KickedPlayer_C;

SDK_NAMESPACE_END
