#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CursorIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CursorIcon.WBP_CursorIcon_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_CursorIcon_C final : public UHUDIconWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CursorIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CursorIcon_C")
	}
	static class UWBP_CursorIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CursorIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CursorIcon_C;

SDK_NAMESPACE_END
