#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickTextBox

#include "Basic.hpp"

#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BrickTextBox.WBP_BrickTextBox_C.UpdateIsPassword
// 0x0001 (0x0001 - 0x0000)
struct WBP_BrickTextBox_C_UpdateIsPassword final
{
public:
	bool                                          bNewIsPassword_UpdateIsPassword;                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_BrickTextBox_C_UpdateIsPassword;

// Function WBP_BrickTextBox.WBP_BrickTextBox_C.UpdatePasswordVisible
// 0x0001 (0x0001 - 0x0000)
struct WBP_BrickTextBox_C_UpdatePasswordVisible final
{
public:
	bool                                          bNewVisible_UpdatePasswordVisible;                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_BrickTextBox_C_UpdatePasswordVisible;

// Function WBP_BrickTextBox.WBP_BrickTextBox_C.ExecuteUbergraph_WBP_BrickTextBox
// 0x0088 (0x0088 - 0x0000)
struct WBP_BrickTextBox_C_ExecuteUbergraph_WBP_BrickTextBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable;                          // 0x0008(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              Temp_softobject_Variable_1;                        // 0x0030(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_Event_bNewIsPassword;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bNewVisible;                          // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5B[0x5];                                       // 0x005B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              K2Node_Select_Default_1;                           // 0x0060(0x0028)(UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BrickTextBox_C_ExecuteUbergraph_WBP_BrickTextBox;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
