#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CameraDashboard

#include "Basic.hpp"

#include "WBP_Dashboard_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CameraDashboard.WBP_CameraDashboard_C
// 0x0008 (0x0328 - 0x0320)
class UWBP_CameraDashboard_C final : public UWBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_CameraDashboard_C;              // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AddFreeCameraElements(class ABrickPlayerController* PC);
	void AddVehicleCameraElements(class USeatBrick* Seat);
	void AddSlomoElements(class ABrickPlayerController* PC);
	void AddActions(class ABrickPlayerController* PC);
	void SetDashboardVisible(bool bNewVisible);
	void PopulateDashboard();
	void Construct();
	void OnSlomoChanged();
	void Destruct();
	void OnIsInFreeCamChanged(bool bNewIsInFreeCam);
	void OnFadeOutTimer();
	void OnProjectileCameraEnabledChanged(bool bNewProjectileCameraEnabled);
	void ExecuteUbergraph_WBP_CameraDashboard(int32 EntryPoint);

	bool ShouldBeVisible() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CameraDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CameraDashboard_C")
	}
	static class UWBP_CameraDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CameraDashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CameraDashboard_C;

SDK_NAMESPACE_END
