#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuButtonPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MenuButtonPanel.WBP_MenuButtonPanel_C
// 0x0010 (0x02A0 - 0x0290)
class UWBP_MenuButtonPanel_C final : public UMenuButtonPanelWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bFillWidth;                                        // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_MenuButtonPanel(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MenuButtonPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MenuButtonPanel_C")
	}
	static class UWBP_MenuButtonPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuButtonPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MenuButtonPanel_C;

SDK_NAMESPACE_END
