#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Player

#include "Basic.hpp"

#include "Slate_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Player.WBP_Player_C.AddRestrictedAreaWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_C_AddRestrictedAreaWidget final
{
public:
	class URestrictedAreaWidget*                  InWidget_AddRestrictedAreaWidget;                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_AddRestrictedAreaWidget;

// Function WBP_Player.WBP_Player_C.AddCrosshairWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_C_AddCrosshairWidget final
{
public:
	class UCrosshairWidget*                       InWidget_AddCrosshairWidget;                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_AddCrosshairWidget;

// Function WBP_Player.WBP_Player_C.AddCameraBrickWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_C_AddCameraBrickWidget final
{
public:
	class UCameraBrickWidget*                     InWidget_AddCameraBrickWidget;                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_AddCameraBrickWidget;

// Function WBP_Player.WBP_Player_C.AddCharacterDashboardWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_C_AddCharacterDashboardWidget final
{
public:
	class UUserWidget*                            InWidget_AddCharacterDashboardWidget;              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_AddCharacterDashboardWidget;

// Function WBP_Player.WBP_Player_C.AddVehicleDashboardWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_C_AddVehicleDashboardWidget final
{
public:
	class UUserWidget*                            InWidget_AddVehicleDashboardWidget;                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_AddVehicleDashboardWidget;

// Function WBP_Player.WBP_Player_C.ExecuteUbergraph_WBP_Player
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_Player_C_ExecuteUbergraph_WBP_Player final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            K2Node_Event_InWidget;                             // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0010(0x0010)(NoDestructor)
	struct FAnchors                               K2Node_MakeStruct_Anchors_1;                       // 0x0020(0x0010)(NoDestructor)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue;             // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors_2;                       // 0x0038(0x0010)(NoDestructor)
	struct FAnchors                               K2Node_MakeStruct_Anchors_3;                       // 0x0048(0x0010)(NoDestructor)
	class URestrictedAreaWidget*                  K2Node_Event_InWidget_4;                           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCrosshairWidget*                       K2Node_Event_InWidget_3;                           // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue_1;           // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue_2;           // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors_4;                       // 0x0078(0x0010)(NoDestructor)
	class UCameraBrickWidget*                     K2Node_Event_InWidget_2;                           // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue_3;           // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            K2Node_Event_InWidget_1;                           // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue_4;           // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Player_C_ExecuteUbergraph_WBP_Player;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
