#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CharacterDashboard

#include "Basic.hpp"

#include "WBP_Dashboard_classes.hpp"
#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CharacterDashboard.WBP_CharacterDashboard_C
// 0x0018 (0x0338 - 0x0320)
class UWBP_CharacterDashboard_C final : public UWBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_CharacterDashboard_C;           // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_DashboardSlider_C*                 HealthSlider;                                      // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 AmmoSlider;                                        // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddCharacterElements(class ABrickPlayerController* PC);
	void AddCurrentItemElements();
	void SetHealth(float Value, bool bCanBeDamaged);
	void AddActionsAndSliders();
	void Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick);
	void UpdateAmmo();
	void PopulateDashboard();
	void ExecuteUbergraph_WBP_CharacterDashboard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CharacterDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CharacterDashboard_C")
	}
	static class UWBP_CharacterDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CharacterDashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CharacterDashboard_C;

SDK_NAMESPACE_END
