#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DashboardBorder

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DashboardBorder.WBP_DashboardBorder_C
// 0x0018 (0x0278 - 0x0260)
class UWBP_DashboardBorder_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           Border;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        TextBlock;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void InitBorder(const class FText& InText, EHorizontalAlignment InHorizontalAlignment, bool bInIsTitle);
	void ExecuteUbergraph_WBP_DashboardBorder(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DashboardBorder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DashboardBorder_C")
	}
	static class UWBP_DashboardBorder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DashboardBorder_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DashboardBorder_C;

SDK_NAMESPACE_END
