#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputMappingKey

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputMappingKey.WBP_InputMappingKey_C
// 0x0010 (0x02C8 - 0x02B8)
class UWBP_InputMappingKey_C final : public UInputMappingKeyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickImage*                            HoldKeyImage;                                      // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InputMappingKey(int32 EntryPoint);
	void UpdateIsHoldAction(bool bNewHold);
	void UpdateConflictedState(bool bNewConflicted);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputMappingKey_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputMappingKey_C")
	}
	static class UWBP_InputMappingKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputMappingKey_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputMappingKey_C;

SDK_NAMESPACE_END
