#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickEditor_TopDashboard

#include "Basic.hpp"

#include "WBP_Dashboard_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickEditor_TopDashboard.WBP_BrickEditor_TopDashboard_C
// 0x0008 (0x0328 - 0x0320)
class UWBP_BrickEditor_TopDashboard_C final : public UWBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_BrickEditor_TopDashboard_C;     // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void PopulateDashboard();
	void ExecuteUbergraph_WBP_BrickEditor_TopDashboard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickEditor_TopDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickEditor_TopDashboard_C")
	}
	static class UWBP_BrickEditor_TopDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickEditor_TopDashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickEditor_TopDashboard_C;

SDK_NAMESPACE_END
